# SPDX-FileCopyrightText: ©  2019 Jesper Dangaard Brouer <https://github.com/netoptimizer> and XDP-Project contributors
# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

USER_TARGETS := xdp_pass_user
XDP_TARGETS := xdp_pass_kern

COMMON_DIR = ../common

include $(COMMON_DIR)/common.mk
